# Site settings
title: ®om's blog
description: Un blog libre
tagline: "{ un blog libre }"
url: "https://blog.rom1v.com"
assets: /assets
paginate: 10
comments_form: true

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/

author:
  name: Romain Vimont
  email: rom@rom1v.com

gems: [jekyll-paginate]
