# Site settings
title: ®om's blog
description: Un blog libre
tagline: "{ un blog libre }"
url: "http://blog.rom1v.com"
assets: /assets
paginate: 10

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/

author:
  name: Romain Vimont
  email: rom@rom1v.com
