- id: 1
  author: Nicolas
  author-url: http://nicolas.dutertry.com
  date: 2010-03-28 09:21:06+01:00
  contents: |
    Le chiffrement des données en SSL étant une opération couteuse, on préfère
    compresser les données avant de les chiffrer pour gagner du temps. D'ou le
    comportement par défaut d'Apache qui compresse tout ce qui passe par HTTPS
    ayant ainsi un volume moins important à chiffrer.

    Mais c'est vrai que cela semble inutile pour ogg.
- id: 2
  author: gut
  date: 2010-04-01 00:06:35+01:00
  contents: |
    Cela ne risque pas de rendre la page "moins sur": le navigateur décidant que
    l'un des éléments s'étant pas couvert par le protocole https ??
- id: 3
  author: ®om
  date: 2010-04-01 06:44:14+01:00
  contents: |
    Seule la compression est désactivée pour la vidéo, le chiffrement est
    toujours là…
- id: 4
  author: gut
  date: 2010-04-02 22:54:53+01:00
  contents: |
    Merci
